# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Soma acumulada com reinício em zero
#'
#' Calcula a estatística CUSUM unilateral superior de uma série: a soma
#' acumulada dos desvios acima de `k`, reiniciada em zero sempre que fica
#' negativa.
#'
#' @param x Vetor numérico com a série.
#' @param k Valor de referência subtraído de cada observação.
#'
#' @returns Um vetor numérico do comprimento de `x`.
#'
#' @export
#'
#' @examples
#' cusum(c(0.2, 1.4, 0.9, -0.3, 1.8), k = 0.5)
cusum <- function(x, k) {
    .Call(`_meupacote_cusum`, x, k)
}

